### ISSUE TITLE
Update "create" event template 

### ISSUE THREAD

**Issue by clemsos** [protocultural/protocultural.org#19]
/create page should be more straightforward.

* What
* Who
* Where
* When
* Why
* How

**Comment by clemsos** [comment]
should be /recipe

**Comment by rejon** [comment]
I like it chef

**Comment by clemsos** [comment]
http://protocultural.org/create/

**Comment by rejon** [comment]
This is closed now right? So you type the stuff in on main page, the page
is generated, and then there is a new event, right?

**Comment by clemsos** [comment]
not really. so far the form is fake, so nothing gets created with it. It is just the process. we don't have a db or anything

**Comment by clemsos** [comment]
but the text on the /create page is quite up-to-date

**Comment by clemsos** [comment]
see #35

**Comment by rejon** [comment]
Ah maybe then just can have a copy n paste box that says email this to info@
and we will create your page and give you git access

**Comment by clemsos** [comment]
yes, or maybe better we have a real form with a mailgun ?

**Comment by rejon** [comment]
Could do, all longer term haha, just thinking of the fastest way to close
this out and so people send their request somewhere and its not a dead end
;)

**Comment by clemsos** [comment]
Yo did a basic emailing system with some online service so it will email the content of the form to us
test here : http://protocultural.org/create/?place=LYON&hashtag=3RDHAND&day=Sat+Mar+26+2016

**Comment by rejon** [comment]
pimp!
