### ISSUE TITLE
Layout should reflect Protocultural PLACE #HASHTAG structure

### ISSUE THREAD

**Issue by clemsos** [protocultural/protocultural.org#22]
Header could be Protocultural PLACE #HASHTAG where PLACE and #HASHTAG are html select

**Comment by rejon** [comment]
Yes but also the hashtag might change when we do an event in a city again,
so it's more event specific

**Comment by clemsos** [comment]
Actually I meant the nav. We should be able to browse 1) by city 2 ) by projects/hashtags

**Comment by clemsos** [comment]
New layout 

![selection_071](https://cloud.githubusercontent.com/assets/743246/13217537/794660fc-d963-11e5-809b-3e639d4a0e0f.png)

**Comment by clemsos** [comment]
ok done
