### ISSUE TITLE
Add newsletter subscription form

### ISSUE THREAD

**Issue by lurnid** [protocultural/protocultural.org#4]
We need a newsletter subscription form for the website.

A number of people have expressed an interest in receiving updates about the project and notification of upcoming events.

**Comment by lurnid** [comment]
@christopheradams @clemsos do you have any existing accounts with an email marketing provider (e.g. mailchimp.com, campaignmonitor.com)?

**Comment by clemsos** [comment]
NewPalmyra use tinyletter. Looks fine with me

**Comment by christopheradams** [comment]
Fixed in commit 0234568
